name: sueltito
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  intl: ^0.19.0
  nfc_manager: ^3.5.0
  cloud_firestore: ^6.0.0
  flutter_secure_storage: ^9.2.2
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  pinput: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/brand_logo.png
