// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJTFdNXK2PF8gabLqHa_tZkQTBnVpPMis',
    appId: '1:403250644361:web:ae41cb20e31b4a5bfdcd58',
    messagingSenderId: '403250644361',
    projectId: 'sueltitoapp',
    authDomain: 'sueltitoapp.firebaseapp.com',
    storageBucket: 'sueltitoapp.firebasestorage.app',
    measurementId: 'G-VPLXEZKD8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9XLu-eyt8fmbKunJgR8CWB0jERa7Pr6s',
    appId: '1:403250644361:android:a2f835976aad5330fdcd58',
    messagingSenderId: '403250644361',
    projectId: 'sueltitoapp',
    storageBucket: 'sueltitoapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTFDbr26s761idhkjFFqfnWvUZ-e_57ew',
    appId: '1:403250644361:ios:9840d5cd11311830fdcd58',
    messagingSenderId: '403250644361',
    projectId: 'sueltitoapp',
    storageBucket: 'sueltitoapp.firebasestorage.app',
    iosBundleId: 'com.example.sueltito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTFDbr26s761idhkjFFqfnWvUZ-e_57ew',
    appId: '1:403250644361:ios:9840d5cd11311830fdcd58',
    messagingSenderId: '403250644361',
    projectId: 'sueltitoapp',
    storageBucket: 'sueltitoapp.firebasestorage.app',
    iosBundleId: 'com.example.sueltito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJTFdNXK2PF8gabLqHa_tZkQTBnVpPMis',
    appId: '1:403250644361:web:a40a508c4d3f2063fdcd58',
    messagingSenderId: '403250644361',
    projectId: 'sueltitoapp',
    authDomain: 'sueltitoapp.firebaseapp.com',
    storageBucket: 'sueltitoapp.firebasestorage.app',
    measurementId: 'G-1DEXQWEW62',
  );
}
